"""Defines constants used through the application"""

BALL_RADIUS = 10

# Mass
BALL_MASS = 1
PADDLE_MASS = 3

# Field size
FIELD_HEIGHT = 600
FIELD_WIDTH = 800
WALL_THICKNESS = 20
PADDLE_HEIGHT = 70
PADDLE_WIDTH = 10
PADDLE_MARGIN = 10

# Control tuning
PADDLE_CONTROL_FORCE = 30

# Collision types
BALL_COLLISION_TYPE = 2
PADDLE_COLLISION_TYPE = 4
VOID_LEFT_COLLISION_TYPE = 8
VOID_RIGHT_COLLISION_TYPE = 16
WALL_COLLISION_TYPE = 32
